export const PROJECT_CONCEPTS = [
  { label: '모노톤', id: 'PC-001' },
  { label: '신비로운', id: 'PC-002' },
  { label: '레트로', id: 'PC-003' },
  { label: '스냅', id: 'PC-004' },
  { label: '스트릿', id: 'PC-005' },
  { label: '자연', id: 'PC-006' },
  { label: '개화기', id: 'PC-007' },
  { label: '빈티지', id: 'PC-008' },
  { label: '프로필', id: 'PC-009' },
  { label: '바디프로필', id: 'PC-010' },
  { label: '여행', id: 'PC-011' },
  { label: '케이팝', id: 'PC-012' },
  { label: '코스프레', id: 'PC-013' },
];
