name: Synchronize to forked repo
on:
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
          ref: master

      - name: Add remote-url and Merge forked-repo changes
        run: |
          git remote add forked-repo https://osh6006:${{ secrets.ACCESS_TOKEN }}@github.com/osh6006/frame-it-front
          git config user.name osh6006
          git config user.email ohs6006@gmail.com

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo master

      - name: Clean up
        run: |
          git remote remove forked-repo
